### ISSUE TITLE
Can't connect to remote host

### ISSUE THREAD

**Issue by stoerchl** [stuffo/scaleway-ubuntukernel#3]
I followed the installation instructions and after the reboot the machine does not come up again and gives the following messages:

>>> Configuring network...
sed: /var/run/net-eth*: No such file or directory
sed: /var/run/net-eth*: No such file or directory
sed: /var/run/net-eth*: No such file or directory
wget: can't connect to remote host (169.254.42.42): Network is unreachable
wget: can't connect to remote host (169.254.42.42): Network is unreachable

The _can't connect to remote host_ continues almost forever until the machine reboots and gets into the same state again.
If I run the script locally as root it works perfectly fine until the reboot.. do you have any idea what might be the problem? thanks!

**Comment by stuffo** [comment]
Seems like there is no Ethernet available. Maybe the wrong modules loaded?

What is the exact instance type you are running? Find out which Ethernet driver is loaded when it is running the original kernel and add them to REQUIRED_MODULES in the ubuntukernel-load.sh script.

Would also help if you can post the complete output of ubuntukernel-load.sh when running it.

**Comment by stoerchl** [comment]
The instance type I use is C2S.

Yes, the wrong / not all modules were loaded. 
When I execute `sudo lshw -C network ` it tells me that the ethernet device uses the `igb` driver. Therefore I added this module to ubuntukernel-load.sh
With `modinfo .../igb.ko | grep depends` I checked for dependencies and added all of them also to the ubuntukernel-load.sh script.

Additional modules I added to ubuntukernel-load.sh: 
- dca/dca 
- i2c/algos/i2c-algo-bit 
- pps/pps_core 
- ptp/ptp 
- net/ethernet/intel/igb/igb

The complete output of ubuntukernel-load.sh looks as follows:
>root@recorder:~# /usr/bin/ubuntukernel-load.sh 
>Ubuntu kernel version: 4.10.3-041003-generic
>Initrd kernel version: none
>Scaleway initrd: http://169.254.42.24/initrd/initrd-Linux-x86_64-v3.13.0.gz
>\+ get scaleway initrd
>\+ extract scaleway initrd
>\+ add module net/virtio_net to initrd
>\+ add module block/virtio_blk to initrd
>\+ add module block/nbd to initrd
>\+ add module dca/dca to initrd
>\+ add module i2c/algos/i2c-algo-bit to initrd
>\+ add module pps/pps_core to initrd
>\+ add module ptp/ptp to initrd
>\+ add module net/ethernet/intel/igb/igb to initrd
>\+ prepend loading modules before entering scaleway initrd
>\+ rebuild initrd archive
>Kexec engaged. Make it So!

With these modifications it works now and starts into the new kernel! Thanks for your help!

**Comment by stuffo** [comment]
added your fix: https://github.com/stuffo/scaleway-ubuntukernel/commit/2c02970395f7353b38434159601ca521acdb2418

Thanks!
